version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    environment:
      KC_HEALTH_ENABLED: true
      KC_DB_VENDOR: POSTGRES
      KC_DB_ADDR: postgresql-primary
      KC_DB_DATABASE: keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_FRONTEND_URL: "https://sso.argonaut.network/auth"
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - proxy
      - postgresql-primary-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-secure.entrypoints=https"
      - "traefik.http.routers.keycloak-secure.rule=Host(`sso.argonaut.network`)"
      - "traefik.http.routers.keycloak-secure.tls=true"
      - "traefik.docker.network=proxy"
      
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
  postgresql-primary-backend:
    external: true
